### ISSUE TITLE
Bug with Cancel queue for building or research

### ISSUE THREAD

**Issue by spartaelcid** [HikeGame/2moons-2.0#11]
Hello,
when i try to cancel some items in the queue of research lab or buildings i have this error:

Message: DateTime::setTimestamp() expects parameter 1 to be integer, float given
File: /includes/GeneralFunctions.php
Line: 143
URL: https://spacewarlords.com/game.php?page=buildings
PHP-Version: 7.2.10-0ubuntu0.18.04.1
PHP-API: apache2handler
2Moons Version: 2.0.git
Debug Backtrace:
#0 [internal function]: errorHandler(2, 'DateTime::setTi...', '/i...', 143, Array)
#1 /includes/GeneralFunctions.php(143): DateTime->setTimestamp(INF)
#2 /includes/pages/game/ShowBuildingsPage.class.php(231): _date('U', INF, 'Europe/Berlin')
#3 /includes/pages/game/ShowBuildingsPage.class.php(271): ShowBuildingsPage->getQueueData()
#4 /game.php(57): ShowBuildingsPage->show()
#5 {main}

**Comment by yamilrh** [comment]
you can show what that line contains
