### ISSUE TITLE
Fehlermeldung beim Abrrechen einer Forschung

### ISSUE THREAD

**Issue by Zulsaframano** [HikeGame/2moons-2.0#3]
Diese Fehlermeldung kommt wenn man eine Forschung abbrechen möchte.

Message: Undefined offset: 113
File: /includes/pages/game/ShowResearchPage.class.php
Line: 61
PHP-Version: 5.6.33
PHP-API: cgi-fcgi
2Moons Version: 2.0.git
Debug Backtrace:
#0 /includes/pages/game/ShowResearchPage.class.php(61): errorHandler(8, 'Undefined offse...', 'FILEPATH ...', 61, Array)
#1 /includes/pages/game/ShowResearchPage.class.php(342): ShowResearchPage->CancelBuildingFromQueue()
#2 /game.php(44): ShowResearchPage->show()
#3 {main}

**Comment by HikeGame** [comment]
Ja das ist schon Post wir werden das Problem beheben

**Comment by mys** [comment]
I believe https://github.com/steemnova/steemnova/pull/3 is the fix. Same issue happened, but the error occuring at different line.

Description
https://utopian.io/utopian-io/@mys/steemnova-impossible-to-cancel-buildings-research-queue-bugfix

**Comment by Instinkt-Servers** [comment]
Same Error here.
