### ISSUE TITLE
Error on creating Admin account

### ISSUE THREAD

**Issue by Kopertje** [HikeGame/2moons-2.0#9]
Hi there!

I just pulled this Git on my Plesk Onyx webserver with php 7.2. The installation goes fine until the creation of the admin account. I get the following error:
**Message**: Position is not empty: 1:1:2!
**File**: /includes/classes/PlayerUtil.class.php
**Line**: 98
**URL**: ?mode=install&step=8
**PHP-Version:** 7.2.7
**PHP-API**: fpm-fcgi
**2Moons Version**: 2.0.0 (FILE)
**Debug Backtrace**:
#0 /install/index.php(574): PlayerUtil::createPlayer(1, '_username_', '_password_.', '_email_', 'en', 1, 1, 2, NULL, 3)
#1 {main}

Is there anyone with the same issue? Or is there already a solution for this and im doing something wrong?

With kind regrads,
Kopertje

**Comment by mys** [comment]
Do You install 2moons on fresh SQL database? Seems that admin player already exist.

**Comment by Kopertje** [comment]
After a fresh install it worked. Other question, not everyhting is loaded over HTTPS.. maybe this can be fixed in the next release?

**Comment by mys** [comment]
HTTPS is only depend on Apache/nginx configuration.

**Comment by Kopertje** [comment]
Some external sources like the Google jsapi is not loaded over HTTPS, in "/styles/templates/adm/ OverviewBody.tpl"

**Comment by HikeGame** [comment]
Hello your mistake is that the position in the galaxy is already occupied

**Comment by alfieo** [comment]
SQLSTATE[42000] I am getting this violation error when creating admin account. It is referring to a lot of AND statement being used QUERY.

**Comment by alfieo** [comment]
Message: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'system = '1' AND planet = '2' AND planet_type = '1'' at line 5

Query-Code:SELECT COUNT(*) as record FROM uni1_planets WHERE universe = 1 AND galaxy = 1 AND system = 1 AND planet = 2 AND planet_type = 1;
File: /includes/classes/Database.class.php
Line: 126
URL: http://2moons.localhost/install/index.php?mode=install&step=8
PHP-Version: 7.2.34-35+ubuntu22.04.1+deb.sury.org+2
PHP-API: fpm-fcgi
2Moons Version: 2.0.0 (FILE)
Debug Backtrace:
#0 /includes/classes/Database.class.php(202): Database->_query('SELECT COUNT(*)...', Array, 'select')
#1 /includes/classes/PlayerUtil.class.php(50): Database->selectSingle('SELECT COUNT(*)...', Array, 'record')
#2 /includes/classes/PlayerUtil.class.php(96): PlayerUtil::isPositionFree(1, 1, 1, 2)
#3 /install/index.php(574): PlayerUtil::createPlayer(1, 'alfieo', '$2a$09$reqtA6ph...', 'alfieo@gmail.co...', 'en', 1, 1, 2, NULL, 3)
#4 {main}

**Comment by HikeGame** [comment]
hello, yes I have to redo the installation part which had to work badly under certain php versions.  Also check in your users and planets table if it hasn't already been created.

**Comment by alfieo** [comment]
Hi, Thank you for the quick response. No it's not created. Before it got created the error shows so it's empty.

**Comment by HikeGame** [comment]
I will take a closer look at the error in the evening, the installation went well for me under php 7.4
